### PR TITLE
Add trash-list default sort by deletion date

### LINKED ISSUE #266: sort the output of trash-list by DeletionDate first
When I do `trash-list`, the sorting is unexpected. It is not sorted alphabetically nor by deletion date. Is there something I am missing here?

### PR DESCRIPTION
**Pull request by Susensio**
Fixes #266 
I had to consume the generated list to be able to sort it and print it afterwards.

### CODE REVIEW

**Comment by andreafrancia** [comment]
Thank for your code!
Can you also add a `--sort={none,date}` option?
For now none should be the default.

**Comment by Susensio** [comment]
I'll look into it. I've seen that `trash-restore` does this sorting as well. Maybe it's a good idea to refactor both and share the code for list generation. What do you think?

**Comment by andreafrancia** [comment]
Choose the way you feel more comfortable with, for me is ok.
If you can refactor in order to prevent duplication between `trash-restore` and `trash-list` it would be great, but is not mandatory, I can remove duplication later.

The trash-restore code for sorting of date is not tested yet. If you decide to refactor trash-restore please use extra care in checking that the sort will continue working. If you can also add test for date sorting ti would be great.

**Comment by andreafrancia** [comment]
Thank you, but I see some conflicts.

**Comment by juanMarinero** [comment]
**Z**sh workaround

```
#!/usr/bin/env zsh

trash-list() {
    # Initialize variables to track options
    local sort_by_time=false
    local sort_by_path=false
    local other_args=()

    # Loop through all arguments
    for ((i = 1; i <= $#; i++)); do
        arg="${@:$i:1}"  # Get the current argument

        case "$arg" in
            --sort)
                # Check if there is a next argument
                if (( i < $# )); then
                    next_arg="${@:$((i + 1)):1}"  # Get the next argument
                    if [[ "$next_arg" == "time" ]]; then
                        sort_by_time=true
                        ((i++))  # Skip the next argument as it is consumed
                    elif [[ "$next_arg" == "path" ]]; then
                        sort_by_path=true
                        ((i++))  # Skip the next argument as it is consumed
                    else
                        echo "Error: --sort must be followed by 'time' or 'path'."
                        return 1
                    fi
                else
                    echo "Error: --sort must be followed by 'time' or 'path'."
                    return 1
                fi
                ;;
            *)
                other_args+=("$arg")  # Collect other arguments. See "man trash-list"
                ;;
        esac
    done

    # Execute the actual 'trash-list' command with the collected arguments
    if [[ "$sort_by_time" == true ]]; then
        command trash-list "${other_args[@]}" | sort -k1,2
    else
        # Default behavior: sort by file path (3rd column)
        command trash-list "${other_args[@]}" | sort -k3,3
    fi
}

```

Call example: `trash-list --trash-dir $HOME/.local/share/Trash --sort time`

**Comment by juanMarinero** [comment]
Taking advance of my previous comment, i.e. sorting `trash-list` by time (date), we can improve `trash-empty` user-friendliness.

```
#!/usr/bin/env zsh

trash-empty() {
    if [ $# -eq 0 ]; then
        echo -e "\ntrash-list content:\n"
        trash-list
    else
        # Check if the first argument is a valid number of days
        if ! [[ "$1" =~ ^[0-9]+$ ]]; then
            echo "Error: Please provide a valid number of days."
            return 1
        fi

        # Set days and calculate cutoff date
        days="$1"
        cutoff_date=$(date -d "$days days ago" +%Y-%m-%d)

        # List files in trash that are older than the cutoff date
        echo -e "\nFiles older than $days days:\n"

        # Use awk to compare only the date part (first column) with cutoff_date
        # "--sort" added in "trash-list" workaround:
        # https://github.com/andreafrancia/trash-cli/pull/274#issuecomment-2480682217
        trash-list --sort time | awk -v cutoff="$cutoff_date" "
            {
                file_date = substr(\$1, 1, 10)
                if (file_date < cutoff) {
                    print \$0
                }
            }"
    fi

    echo -e "\nPERMANENTLY EMPTY these files from trash? (y|n):\n"
    read confirm
    if [[ $confirm == [yY] ]]; then
      command trash-empty "$1"
    else
      echo "Operation cancelled."
    fi
}
```
Call examples:

- show all to remove and ask confirmation: `trash-empty`
- show all older than 7 day in trash and ask confirmation to remove: `trash-empty 7`

Note: ideally all this or alike should be implemented in the Python-repo. Summary:
- a flag `--sort` to `trash-list` to sort by path, time, file-extension, size, etc.
- an `-i` flag to prompt before every `trash-empty` or `trash-rm` removal like in `rm`
- Maybe also a `--verbose` flag to `trash-empty` (and `trash-rm`), this would run code alike my `trash-empty` function above

**Pull request closed without merging**
