### PR TITLE
Add command list to help menu

### PR DESCRIPTION
**Pull request by joemas08**
This pull request adds the command list mentioned in issue #241.
This is also my first open source contribution so if I have missed anything I apologize.

### CODE REVIEW

**Review by antonkesy — CHANGES_REQUESTED** [review]
Shouldn't argparse be able to generate this on its own? [official argparse example](https://docs.python.org/3/library/argparse.html#example)

+

this line is definitely too long

**Review by antonkesy — CHANGES_REQUESTED** [review]
Shouldn't argparse be able to generate this on its own? [official argparse example](https://docs.python.org/3/library/argparse.html#example)

and

this line is too long

**Comment by joemas08** [comment]
Appreciate your comment. As I am still acquainting myself with argparse, if there are specific argparse features I may have overlooked, please feel free to provide guidance. Open to refining the implementation based on your insights.

**Comment by andreafrancia** [comment]
Thank you @joemas08
I'm having problem on merging, can you please recreate a new pull request from master?
Thank you

**Comment by andreafrancia** [comment]
I managed to merge, sorry, I'm still learning.

**Comment by joemas08** [comment]
No worries @andreafrancia 
I'm glad I could be of help.

**Pull request merged**
