### PR TITLE
Fix links to trash specification

### PR DESCRIPTION
**Pull request by dreua**
Closes: https://github.com/andreafrancia/trash-cli/issues/231

`grep -lr ramend . | xargs sed -i 's#http://www\.ramendik\.ru/docs/trashspec\.html#https://specifications.freedesktop.org/trash-spec/trashspec-1.0.html#g'`

### CODE REVIEW

**Comment by andreafrancia** [comment]
Thank you, can you remove the modification of docs/trashspec-0.7.html

**Comment by dreua** [comment]
Oft course but could you hint me to why the change would be unwanted there?

**Comment by andreafrancia** [comment]
In the beginning the "Trash Specs" where kept at http://www.ramendik.ru/docs/trashspec.html, this was the version 0.7.
I downloaded this version in the docs dir and I used it for the implementation of trash-cli.
Then the "Trash Specs" were updated to the version 1.0 and moved to the freedesktop.org site.

The docs/trashspec-0.7.html file is a download of the original version which was hosted on http://www.ramendik.ru/docs/trashspec.html

We have two options here:
 1) keep the docs/trashspec-0.7.html as is
 2) delete the old docs/trashspec-0.7.html and download the latest version (1.0) from freedesktop.

If you want you can include in the PR the changes for the option 2.

**Comment by dreua** [comment]
Of course that is just an archived html, should have seen that in the first place :facepalm: 
I went with option 1, would you want me to squash/rebase or anything?

**Pull request merged**
