### PR TITLE
Simple maintenance improvements

### PR DESCRIPTION
**Pull request by a1346054**
This is a continuation from #212 with better explanations in commit messages.

I've also dropped the commit that fixes whitespace issues.

### CODE REVIEW

**Comment by andreafrancia** [comment]
ok, keep -> | * ed44fa9 Add missing final newline  a1346054, 5 hours ago
no, remove -> | * cb15289 Use license file from gnu.org  a1346054, 1 year ago
no, remove -> | * 2d9e984 Invoke bash through /usr/bin/env  a1346054, 1 year ago
no, remove -> | * 797b80f No need to execute bash to start docker  a1346054, 5 hours ago
ok, keep -> | * f869ed9 Remove executable bit from text files  a1346054, 5 hours ago
good, keep -> | * 18c4cc5 Fix typos  a1346054, 4 hours ago

Please pull the latest master and create a pull request on top of it with the commit I marked with "keep".
About the license, open an issue with the reason of changing the file and the wget/curl command to use to download the license.

About the use of env instead of /bin/bash let's say that the scripts works very well with old bash versions. I'm using a Bash 3. I want to keep scripts compatible with older bash versions.

The same is about using sh instead of bash. I want to be sure bash with all their features. I don't want discover that a bashism works only on some computers but fails in another.

**Comment by andreafrancia** [comment]
In any case thank you for your contribution.

**Comment by a1346054** [comment]
Understood, those commits are now removed.

**Comment by andreafrancia** [comment]
Great work. Thank you!

**Pull request merged**
