### PR TITLE
Sort trash-restore choices

### LINKED ISSUE #98: restore-trash should sort
restore-trash should sort the list of files in trash to make it easier to locate the file you're looking for, especially if you don't remember the exact name.

### PR DESCRIPTION
**Pull request by Self-Perfection**
Fixes #98

### CODE REVIEW

**Comment by andreafrancia** [comment]
Thank you for your patch.

**Comment by nsirolli** [comment]
Thanks! It could help including information about this option in the man page for trash-restore.

Nevertheless, it's not working for me:

> nico@pilar:~> trash-restore --sort=date
> No files trashed from current dir ('/home/nico')

and when I run

> nico@pilar:~> trash-restore

a non empty list of files shows up.

**Comment by andreafrancia** [comment]
Please send me the output of `trash-restore --version`

**Comment by nsirolli** [comment]
> nico@pilar:~> trash-restore --version
> trash-restore 0.17.1.14

I should be running 0.20.11.7, right?

**Comment by andreafrancia** [comment]
Yes, or any older version.

**Pull request merged**
